[package]
authors = ["Sharad Chand <sharad.d.chand@gmail.com>"]
name = "mime-detective"
version = "0.1.2"

[dependencies]
magic = "0.12.2"
mime = "0.3.5"
rocket = { version = "0.3.5", optional = true }

[features]
rocket_data = ["rocket"]